In [2]:
print('I said "I can\'t do it!"')
#print  (‘I said “I can’t do it!”?)
print ('''I said "I can’t do it!"''')
#print (“’I said” I can’t do it!\’\””)
#print (“”I said”I can’t do it!\’\””)
#print (‘I said’+”””+’I can’t “’”+’do it!””)

I said "I can't do it!"
I said "I can’t do it!"


In [19]:
a=(0,1)
b=(1,2)
a=a+b
a

(0, 1, 1, 2)

In [1]:
x=1
print (id(x))
x=x+1
print (id(x))
y=x
print (id(y))
x+=1
print (id(x))
x-=1
print (id(x))

10910400
10910432
10910432
10910464
10910432


In [4]:
import numpy as np
T = np.array([3, 0.1, -6.7])
T

array([ 3. ,  0.1, -6.7])

In [6]:
T = np.linspace(0,1,5)
T

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
T = np.arange(0,1,0.1)
T

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [12]:
T = np.zeros((2,2))
T

array([[0., 0.],
       [0., 0.]])

In [14]:
T = np.ones((2,4))
T

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
T = np.eye(3)
T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
T = np.random.rand(3,3)
T

array([[0.61184071, 0.10393994, 0.38490053],
       [0.72480542, 0.71512443, 0.79027566],
       [0.54752822, 0.32274329, 0.16585933]])

In [17]:
T = np.random.randn(3,3)
T

array([[-1.55805389,  1.63179299,  1.14194283],
       [-0.40282569,  0.52840012,  0.31031857],
       [-1.65028579, -1.15845806, -0.45067032]])